// <auto-generated />
using System;
using ICS_Project.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ICS_Project.Db.Migrations
{
    [DbContext(typeof(IcsDbContext))]
    partial class IcsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ICS_Project.Db.Entities.CommentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AuthorId");

                    b.Property<string>("Content");

                    b.Property<Guid?>("PostEntityId");

                    b.Property<DateTime>("Timestamp");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PostEntityId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("ICS_Project.Db.Entities.PostEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AuthorId");

                    b.Property<string>("Content");

                    b.Property<Guid?>("TeamEntityId");

                    b.Property<DateTime>("Timestamp");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("TeamEntityId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("ICS_Project.Db.Entities.TeamEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AdminId");

                    b.Property<string>("Category");

                    b.Property<string>("Description");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("ICS_Project.Db.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Nickname");

                    b.Property<string>("Password");

                    b.Property<string>("Salt");

                    b.Property<Guid?>("TeamEntityId");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("TeamEntityId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ICS_Project.Db.Entities.CommentEntity", b =>
                {
                    b.HasOne("ICS_Project.Db.Entities.UserEntity", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("ICS_Project.Db.Entities.PostEntity")
                        .WithMany("Comments")
                        .HasForeignKey("PostEntityId");
                });

            modelBuilder.Entity("ICS_Project.Db.Entities.PostEntity", b =>
                {
                    b.HasOne("ICS_Project.Db.Entities.UserEntity", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("ICS_Project.Db.Entities.TeamEntity")
                        .WithMany("Posts")
                        .HasForeignKey("TeamEntityId");
                });

            modelBuilder.Entity("ICS_Project.Db.Entities.TeamEntity", b =>
                {
                    b.HasOne("ICS_Project.Db.Entities.UserEntity", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId");
                });

            modelBuilder.Entity("ICS_Project.Db.Entities.UserEntity", b =>
                {
                    b.HasOne("ICS_Project.Db.Entities.TeamEntity")
                        .WithMany("Users")
                        .HasForeignKey("TeamEntityId");
                });
#pragma warning restore 612, 618
        }
    }
}
